Resources:
  InventoryManagementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "IM-Location"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: "location"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST