@startuml
title Delete Warehouse

actor Client
participant APIGateway
participant Lambda
participant DeleteWarehouse
participant WarehouseDao
database Database

Client -> APIGateway : POST / Item
activate Client
APIGateway -> Lambda
activate Lambda
Lambda -> DeleteWarehouse :  handleRequest(CreateItemRequest, Context)
activate DeleteWarehouse

DeleteWarehouse -> WarehouseDao : loadWarehouse(item)
activate WarehouseDao

WarehouseDao -> Database : Load Warehouse

alt if Warehouse Not Empty
    WarehouseDao <-- Database : false
    DeleteWarehouse <-- WarehouseDao : false
    Lambda <-- DeleteWarehouse : throw WarehouseNotEmptyException
    APIGateway <-- Lambda
    Client <-- APIGateway : 4xx Response
else otherwise, continue
end

alt if name Does Not Exist
    WarehouseDao <-- Database : false
    DeleteWarehouse <-- WarehouseDao : false
    Lambda <-- DeleteWarehouse : throw WarehouseNotFoundException
    APIGateway <-- Lambda
    Client <-- APIGateway : 4xx Response
else otherwise, continue
end

WarehouseDao <-- Database : Warehouse
DeleteWarehouse <-- WarehouseDao : Warehouse
DeleteWarehouse -> WarehouseDao : deleteWarehouse(name)
WarehouseDao -> Database : Delete Warehouse

deactivate WarehouseDao

Lambda <-- DeleteWarehouse : DeleteWarehouseResult
deactivate DeleteWarehouse
APIGateway <-- Lambda
deactivate Lambda
Client <-- APIGateway : 200 Response
deactivate Client

@enduml
