@startuml
title Delete Warehouse

actor Client
participant APIGateway
participant Lambda
participant DeleteItem
participant ItemDao
database Database

Client -> APIGateway : POST / Item
activate Client
APIGateway -> Lambda
activate Lambda
Lambda -> DeleteItem :  handleRequest(DeleteItemRequest, Context)
activate DeleteItem

DeleteItem -> ItemDao : deleteItem(item)
activate ItemDao

ItemDao -> Database : Delete Item

alt if name Does Not Exist
    ItemDao <-- Database : false
    DeleteItem <-- ItemDao : false
    deactivate ItemDao
    Lambda <-- DeleteItem : throw ItemNotFoundException
    APIGateway <-- Lambda
    Client <-- APIGateway : 4xx Response
else otherwise, continue
end

Lambda <-- DeleteItem : DeleteItemResult
deactivate DeleteItem
APIGateway <-- Lambda
deactivate Lambda
Client <-- APIGateway : 200 Response
deactivate Client

@enduml
