@startuml
title DELETE ITEM

actor Client
participant APIGateway
participant Lambda
participant DeleteItemService
participant ItemDao
database Database

Client -> APIGateway : POST / Item
activate Client
APIGateway -> Lambda
activate Lambda
Lambda -> DeleteItemService :  handleRequest(Controller, Context)
activate DeleteItemService


DeleteItemService -> ItemDao : deleteItem(item)
activate ItemDao

ItemDao -> Database : delete

alt if name Does Not Exist
    ItemDao <-- Database : false
    DeleteItemService <-- ItemDao : false
    deactivate ItemDao
    Lambda <-- DeleteItemService : throw ItemNotFoundException
    APIGateway <-- Lambda
    Client <-- APIGateway : 4xx Response
else otherwise, continue
end

Lambda <-- DeleteItemService : handleRequest(Controller, Context)
deactivate DeleteItemService
APIGateway <-- Lambda
deactivate Lambda
Client <-- APIGateway : 200 Response
deactivate Client

@enduml
