@startuml
title GET ITEM

actor Client
participant APIGateway
participant Lambda
participant GetItemService
participant ItemDao
participant ModelConverter
database Database

Client -> APIGateway : POST / Item
activate Client
APIGateway -> Lambda
activate Lambda
Lambda -> GetItemService :  handleRequest(Controller, Context)
activate GetItemService
GetItemService -> ItemDao : find(name)
activate ItemDao
ItemDao -> Database : load

alt if name invalid
    GetItemService <-- Database : false
    Lambda <-- GetItemService : throw ItemNotFoundException
    APIGateway <-- Lambda
    Client <-- APIGateway : 4xx Response
else otherwise, continue
end

ItemDao <- Database : Item

GetItemService <-- ItemDao : Item
deactivate ItemDao

GetItemService -> ModelConverter : itemConverter(item)
activate ModelConverter

GetItemService <-- ModelConverter : ItemModel(Item)
deactivate ModelConverter

Lambda <-- GetItemService : handleRequest(Controller, Context)
deactivate GetItemService
APIGateway <-- Lambda
deactivate Lambda
Client <-- APIGateway : 200 Response
deactivate Client

@enduml
