Resources:
  InventoryManagementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "IM-Item"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "category"
          AttributeType: "S"
        - AttributeName: "availability"
          AttributeType: "S"
        - AttributeName: "location"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "ID-Index"
          KeySchema:
            - AttributeName: "id"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
        - IndexName: "Available-Index"
          KeySchema:
            - AttributeName: "availability"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
        - IndexName: "Category-Index"
          KeySchema:
            - AttributeName: "category"
              KeyType: "HASH"
            - AttributeName: "availability"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
        - IndexName: "Location-Index"
          KeySchema:
            - AttributeName: "location"
              KeyType: "HASH"
            - AttributeName: "category"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL