Resources:
  InventoryManagementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "IM-Item"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: "name"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "category"
          AttributeType: "S"
        - AttributeName: "available"
          AttributeType: "B"
        - AttributeName: "location"
          AttributeType: "B"
      KeySchema:
        - AttributeName: "name"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "IDIndex"
          KeySchema:
            - AttributeName: "id"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
        - IndexName: "AvailableIndex"
          KeySchema:
            - AttributeName: "available"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
        - IndexName: "CategoryIndex"
          KeySchema:
            - AttributeName: "category"
              KeyType: "HASH"
            - AttributeName: "available"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
        - IndexName: "LocationIndex"
          KeySchema:
            - AttributeName: "location"
              KeyType: "HASH"
            - AttributeName: "category"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL