Resources:
  InventoryManagementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "IM-Item"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: "itemName"
          AttributeType: "S"
        - AttributeName: "itemId"
          AttributeType: "S"
        - AttributeName: "itemCategory"
          AttributeType: "S"
        - AttributeName: "availability"
          AttributeType: "S"
        - AttributeName: "itemLocation"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "itemName"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "AvailableIndex"
          KeySchema:
            - AttributeName: "availability"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
        - IndexName: "CategoryIndex"
          KeySchema:
            - AttributeName: "itemCategory"
              KeyType: "HASH"
            - AttributeName: "availability"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
        - IndexName: "LocationIndex"
          KeySchema:
            - AttributeName: "itemLocation"
              KeyType: "HASH"
            - AttributeName: "itemCategory"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL