@startuml
title UPDATE ITEM

actor Client
participant APIGateway
participant Lambda
participant CreateItemService
participant ItemDao
participant ServiceUtility
database Database

Client -> APIGateway : POST / Item
activate Client
APIGateway -> Lambda
activate Lambda
Lambda -> CreateItemService :  handleRequest(Controller, Context)
activate CreateItemService

CreateItemService -> ItemDao : find(name)
activate ItemDao
ItemDao -> Database : load

alt if Item Is Found
    ItemDao <-- Database : false
    CreateItemService <-- ItemDao : false
    Lambda <-- CreateItemService : throw ItemNotFoundException
    APIGateway <-- Lambda
    Client <-- APIGateway : 4xx Response
else otherwise, continue
end

deactivate ServiceUtility

CreateItemService -> CreateItemService : populate Item object

CreateItemService -> ItemDao : save(Item)
activate ItemDao

ItemDao -> Database : save

deactivate ItemDao

Lambda <-- CreateItemService : handleRequest(Controller, Context)
deactivate CreateItemService
APIGateway <-- Lambda
deactivate Lambda
Client <-- APIGateway : 200 Response
deactivate Client

@enduml
